### PR TITLE
fix plugin for volatility 3 framework 2.5.2

### PR DESCRIPTION
**Pull request by ZarKyo**

### CODE REVIEW

**Comment by oshaked1** [comment]
Hi @ZarKyo, could you explain what is the purpose of this change?
I had no issues running the existing plugin with framework version 2.5.2

**Comment by ZarKyo** [comment]
Hi !

I put plugins into `volatility3/volatility3/framework/plugins/linux/` and `volatility3 changes` into `volatility3/volatility3/framework/symbols/linux/`

I tried to use the plugins on a Kali Linux : `Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`

```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.4
Codename:       kali-rolling
```

Python version : `Python 3.11.6`

---

And on an Ubuntu : `Linux ubuntu 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

Python version : `Python 3.10.12` (also tried with `Python 3.12.1`)

---

For both, I have the same error :

```
Volatility 3 Framework 2.5.2
Traceback (most recent call last):
  File "/home/sand/vol3/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/sand/vol3/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/home/sand/vol3/volatility3/volatility3/cli/__init__.py", line 293, in run
    failures = framework.import_files(
  File "/home/sand/vol3/volatility3/volatility3/framework/__init__.py", line 153, in import_files
    failures += import_file(
  File "/home/sand/vol3/volatility3/volatility3/framework/__init__.py", line 185, in import_file
    importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sand/vol3/volatility3/volatility3/framework/plugins/linux/psaux.py", line 11, in <module>
    from volatility3.plugins.linux import pslist
  File "/home/sand/vol3/volatility3/volatility3/framework/plugins/linux/pslist.py", line 59, in <module>
    class PsList(interfaces.plugins.PluginInterface):
  File "/home/sand/vol3/volatility3/volatility3/framework/plugins/linux/pslist.py", line 111, in PsList
    task: symbols.linux.extensions.task_struct,
AttributeError: module 'volatility3.framework.symbols' has no attribute 'linux'
```

I tried using the plugins with an old release of volatility 3 in Kali and Ubuntu. It works.

So my PR allows the plugins to work in these environments (Ubuntu and Kali with their Python version respectively).

Let me know if I'm wrong anywhere.

**Comment by oshaked1** [comment]
I must admit that I don't understand why it doesn't work for you and why it does with your proposed change (I even tried mimicking your environment).
Before I approve your PR, can you make sure that the pslist plugin works for you with the change you made?
The usage of `symbols.linux` which seems to be problematic is present in a few places. The change you made is only for the type annotation which failed on import, but the other ones will only fail when running the plugin.

**Comment by ZarKyo** [comment]
The pslist plugin seems to work for me after the changes. I've tried using other plugins that use pslist and that seems to work as well.

I can understand that you don't want to approve the PR because it works on your end. I can open an issue that will help for those who have the same problem if you prefer

**Pull request merged**
